name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.7.0
  firebase_auth: 4.2.9
  cloud_firestore: 4.4.3
  firebase_storage: 11.0.14
  image_picker: 0.8.6+4
  path_provider: 2.0.13
  convex_bottom_bar: 3.2.0
  geolocator: 9.0.2
  geocoding: 2.0.5
  iconly: 1.0.1
  font_awesome_flutter: 10.4.0
  animated_splash_screen: 1.3.0
  flutter_native_splash: 2.2.19
  syncfusion_flutter_datepicker: 20.4.54
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

flutter_native_splash: 
  color: '#ffffff'
  image: assets/images/logo.png
  android: true

weight: 700
